In [8]:
## Importing the CSV and creation of a dataframe "poke_df"
import pandas as pd
from matplotlib import pyplot as plt

PATH_POKEDEX_CSV = "./pokedex/pokedex.csv"
poke_df = pd.read_csv(PATH_POKEDEX_CSV)

In [9]:
## Listing all the attributes/colname in the dataframe, with their respective datatypes
print(poke_df.columns)

Index(['Unnamed: 0', 'pokedex_number', 'name', 'german_name', 'japanese_name',
       'generation', 'status', 'species', 'type_number', 'type_1', 'type_2',
       'height_m', 'weight_kg', 'abilities_number', 'ability_1', 'ability_2',
       'ability_hidden', 'total_points', 'hp', 'attack', 'defense',
       'sp_attack', 'sp_defense', 'speed', 'catch_rate', 'base_friendship',
       'base_experience', 'growth_rate', 'egg_type_number', 'egg_type_1',
       'egg_type_2', 'percentage_male', 'egg_cycles', 'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fight', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy'],
      dtype='object')

In [10]:
## "Unnamed: 0" is not useful for our case, so we remove the column
poke_df = poke_df.drop("Unnamed: 0", axis=1)
poke_df.head()

,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,type_2,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,Normal,Seed Pokémon,2,Grass,Poison,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,Normal,Seed Pokémon,2,Grass,Poison,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,Poison,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,Poison,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,Normal,Lizard Pokémon,1,Fire,NaN,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5

In [11]:
## Size of the DataFrame: There are 1028 different Pokemons
shape_poke_df = poke_df.shape
print(f"Rows: {shape_poke_df[0]}\nColumns: {shape_poke_df[1]}")

Rows: 1028
Columns: 50

In [13]:
## Generations of Pokemon: 8 (2024)
## According to Bulbapedia: A generation (Japanese: 世代 ( せだい ) generation) is a grouping of the Pokémon games that separates them based on the Pokémon they include.

generations = poke_df["generation"].value_counts().sort_index()
print(generations)

generation
1    192
5    171
3    165
4    121
2    107
7     99
8     88
6     85
Name: count, dtype: int64